PRAGMA foreign_keys = ON;


CREATE TABLE paths(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	loc1 VARCHAR(20) NOT NULL,
	loc2 VARCHAR(20) NOT NULL,
    min INTEGER NOT NULL,
    sec INTEGER NOT NULL,
);